tokio-rs/website

content/docs/getting-started/simple-server.md
Found the repeated word while going through the docs.
=> Fix typo in simple-server docs

content/docs/going-deeper/third-party.md
"allows abstraction Unix signals" doesn't parse, and I think it's simpler to
make both the inotify and signal text consistent and shorter ("maps" rather than
"enables use of").
=> third-party: Fix a typo and reword inotify/signal

layouts/blog/single.html, layouts/docs/single.html
All links in the sidenav currently get the `text-muted` class. This threw me off a bit when I was browsing through documentation.
=> Indicate current page in single page/blog post side nav

layouts/partials/header.html
Fixes #10 . To see the change, open the website in Firefox and note that the "Subscribe to This Page..." option is enabled under the Bookmarks menu.
This puts the link on all pages by default. I don't see any harm in that, but if it should only be on the blog pages, that probably requires some conditional formatting in Hugo that I don't know how to do yet.
=> Add link for blog RSS feed so browsers can see it

content/docs/getting-started/reactor.md
I think `crates` here is meant to be `creates`
=> Fix typo in reactor docs

content/docs/going-deeper/core-low-level.md, content/docs/going-deeper/futures-model.md
This fixes a few small grammar and spelling mistakes that I encountered
while reading the "Going Deeper" documentation.
=> Fix 'going deeper' docs mistakes

content/docs/getting-started/simple-server.md, content/docs/going-deeper/multiplex.md, content/docs/going-deeper/streaming.md
These are identical since rust-lang/rust#37094 landed, and
`extend_from_slice` will be deprecated in the future.
=> Use `extend` instead of `extend_from_slice`

content/docs/getting-started/pipeline-server.md
During compilation a friendly warning informed me that the `service` variable does not need to be mutable.
```
warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
--> src/main.rs:58:13
|
58 |         let mut service = s.new_service()?;
|             ^^^^^^^^^^^
```
=> variable does not need to be mutable.

content/docs/going-deeper/multiplex.md
In Multiplexed protocols page, differ from source code in example.
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>
=> fix typo in Multiplexed protocols

content/docs/going-deeper/third-party.md
I just released the second version of this crate, which is still in an earlier stage of development. Please let me know if there's a level of maturity you require of the crates listed here, and I can re-file the PR at a later stage when the crate has achieved greater stability.
=> add tokio-retry to third-party crates

content/docs/going-deeper/third-party.md
The couchbase SDK is future-driven from the ground up and fits very well into the tokio ecosystem. Here is an example: https://github.com/daschl/tokio-cb/blob/master/src/main.rs
=> Add a note on the async couchbase driver

content/docs/getting-started/simple-server.md
In the simple server example `BufMut` is imported from the bytes crate, but isn't used (`BytesMut` is the only trait needed). Removing the import might improve clarity, but there may have been another reason for the import that I am not aware of.
Thanks. 😄
=> Remove the extra `BufMut` import.

content/docs/getting-started/core.md, content/docs/getting-started/db.md, content/docs/getting-started/futures.md, content/docs/getting-started/pipeline-server.md, content/docs/getting-started/reactor.md, content/docs/getting-started/simple-server.md, content/docs/getting-started/streams-and-sinks.md, content/docs/getting-started/tls.md, content/docs/getting-started/tokio.md, content/docs/going-deeper-futures/futures-mechanics.md, content/docs/going-deeper-futures/futures-model.md, content/docs/going-deeper-futures/returning.md, content/docs/going-deeper-futures/synchronization.md, content/docs/going-deeper-futures/tasks.md, content/docs/going-deeper-tokio/architecture.md, content/docs/going-deeper-tokio/core-low-level.md, content/docs/going-deeper-tokio/examples.md, content/docs/going-deeper-tokio/handshake.md, content/docs/going-deeper-tokio/multiplex.md, content/docs/going-deeper-tokio/streaming.md, content/docs/going-deeper-tokio/third-party.md, content/docs/going-deeper-tokio/transports.md, layouts/docs/single.html
Reorganises the "Going Deeper" section into two:
* "Going Deeper: Futures"
* "Going Deeper: Tokio"
When I found the docs on tokio.rs I was really happy. It was genuinely fun working through the Getting Started section. But I'm finding it hard getting beyond this. One of the problems I noticed is the way the Futures and Tokio content is interleaved has made it a little difficult to absorb and build strong conceptual models.
Tokio is really fascinating but it's a bit ahead of where I am right now. What I want to do is learn the basic facilities for working with async code in Rust first. I've experimented with threads and channels, now I want to study Futures.
So I'm suggesting we separate the two topics. I'm also wondering whether to split the Tokio section into "Going Deeper: tokio-proto" …
=> Split "Going Deeper" section to make it easier to study

content/docs/getting-started/simple-server.md
In the simple server example there are two comments that where not clear to me. This PR updates the comments to be more in line with my understanding (which may or may not be correct). If this is not quite right I would be happy to update it, or just have this closed.
Thanks 😄
=> Clarify the comments above the type aliases in the `ServerProto` impl block

content/docs/getting-started/simple-server.md
While reading the docs and examples i came with an error:
```
|
3 | extern crate tokio_core;
| ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```
Then i noticed that `tokio-core` wasn't referenced on the doc's dependencies.
=> Added tokio-core dependency

content/docs/getting-started/db.md
This PR attempts to improve on the database example in the getting started section by:
1. Adding a section of creating the table that the example will query from
1. Switching from using a `randomNumber` column in a `World` table to a `body` column from a `greetings` table.
The example will now return a random greeting from the table and return a response such as:
```json
{"id":3,"body":"Bonjour"}
```
=> Populate database in getting started db example.

content/docs/going-deeper-tokio/multiplex.md
The buffer does not include the request id anymore, we should read the full buffer. The current implementation removes the first 4 bytes from the line.
=> The requestId has already been red from the buffer

content/docs/going-deeper-futures/synchronization.md
Continuing commit 6a4cb84035317af177066f557911ca68c7762523
- - -
On that note, some static site generators check if linked pages in content are dead or not. But I don't know if any check if an _anchor_ exists or not nor if Hugo has this feature and it is enabled.
=> Fix the non-code portion of the Sender::complete removal.

ci/test.sh
Noticed right off the bat that I couldn't `./` this script. Applied
generally accepted shellchecked lints and recommendations to this
script.
=> Respond to shellcheck lints on ci/test.sh

layouts/docs/single.html, static/css/tokio.css
Hopefully this might encourage more contribution.
This is modeled after https://readthedocs.org/ and many other
documentation sites out there that have a GitHub repo backing them with
a generated link to the backing document.
- - -
Examples from elsewhere:
---
This PR:
=> Add Edit on GitHub Link to documentation pages.

static/css/tokio.css
Maintains mobile layout. Desktop top bar is centered again.
Closes https://github.com/tokio-rs/website/issues/44
=> Recenter Top Nav Bar

content/docs/getting-started/simple-server.md, content/docs/going-deeper-futures/futures-model.md, content/docs/going-deeper-tokio/transports.md
Most of the documentation uses regular comments except for several occurrences of doc comments and seems like there is no reason for later (because documentation is not going to get it's own documentation).
=> [Minor] Replace doc comments with regular ones

content/docs/getting-started/db.md
Double semicolon for double safety. Thanks so much for the awesome documentation, team!
=> Trivial typo

content/docs/getting-started/pipeline-server.md
Change method `Stream::send_all` to `Sink::send_all` and add link
Fix link for `Stream::and_then` method
=> Fix links to Stream::and_then and Sink::send_all methods in "Pipeline server"

content/docs/getting-started/io.md
This fixes the link to the `tokio/reactor` module. The previous link resulted in
> The requested resource does not exist
=> Fix link to reactor doc

content/docs/getting-started/chat.md
tokio_io is the old name. The crate is now called tokio-io.
=> fixed typo in dependency list

LICENSE-APACHE, LICENSE-MIT, README.md
Existing contributions are in the [process](https://github.com/tokio-rs/website/issues/139) of being relicensed. Until then, explicitly have *new* contributions licensed under Apache / MIT.
=> Add a license covering new contributions.

layouts/blog/single.html
Calling reverse on Site Menu with out sorting it lead to strange
behaviour.  The menu order is not the same on every blog page.
I was unable to figure out a way to order by date, so this orders it by
weight.
Thanks @Yoopo for pointing out the issue.
=> Deterministically order blog menu

ci/test.sh, content/blog/2018-03-tokio-runtime.md, content/docs/getting-started/chat.md, content/docs/getting-started/futures.md, content/docs/getting-started/hello-world.md, content/docs/getting-started/io.md, content/docs/getting-started/runtime-model.md, content/docs/getting-started/tasks.md, layouts/index.html
This patch updates the website to use the Tokio runtime instead of
`current_thread`.
=> Update for the runtime release

content/docs/getting-started/chat.md
This fixes a typo I noticed while reading the 'chat' example.
=> Fix typo 'implementation'

content/docs/getting-started/hello-world.md
This is a nothing PR, but I noticed a small inconsistency with the two commands in the hello world example - one using `$` to signal shell and the other not; so this PR just adds the missing `$`.
=> Minor $ tweak for consistency

content/docs/going-deeper/timers.md
Since the Interval is 100 milliseconds and there are 9 such intervals, I think that the total time will be 0.9 seconds, not 9 seconds.
=> Correct runtime of Interval example

content/legacy/getting-started/tokio.md, layouts/docs/single.html
Tokio uses the futures library at futures version 0.1. The sidebar in
the documentation section, however, confusingly pointed to futures
version 0.2. Update the link.
I also checked if there were any other locations where futures was
linked to not using 0.1 explicitely with the following command
grep -rP 'docs.rs/futures(?!/0.1)'
and changed a legacy document, but everything else looks like it is
explicitely linking to the 0.1 version of the docs.
=> Update docs.rs futures link to use futures@0.1

content/docs/getting-started/chat.md
Using `position` method of trait `Iterator` instead of combination of `enumerate`, `find` and `map` methods.
```rust
let pos = self.rd.windows(2)
.position(|bytes| bytes == b"\r\n");
```
=> Simplify finding line delimeter position

config.toml, content/docs/going-deeper/building-runtime.md, layouts/shortcodes/api-url.html
Mostly for educational purposes, as a runtime is already provided.
This should not go in before https://github.com/tokio-rs/tokio/pull/306, as it references that.
=> Describe how one could build one's own runtime

content/docs/going-deeper/building-runtime.md
Just removes an extra `.` at the end of the link.
=> Fix link to mio crate on building a runtime docs page

content/docs/going-deeper/frames.md
Although `tokio_io::codec` works, it is confusing to point people to that because the [docs.rs website for tokio_io](https://docs.rs/tokio-io/0.1.7/tokio_io/) says that there is no `codec` module in `tokio_io`. When I was going through the tutorial this morning, I read this part and wanted to look at the documentation for these traits, but eventually had to go looking through the git history for tokio to find out what was wrong.
=> change tokio_io::codec to tokio_codec in the tutorial

.travis.yml, content/legacy/going-deeper-tokio/core-low-level.md
The issue stems from a file in the legacy directory which does not seem to be a part of the current website. I made the link into an absolute link to fix the issue. There are several other warnings regarding the same issue, but not being familiar with Hugo, I couldn't make a lot of headway with it.
But this fix should allow building the website on the latest version of Hugo.
Fixes #190
=> Fix local website build

config.yaml, content/docs/getting-started/chat.md, content/docs/getting-started/futures.md, content/docs/getting-started/hello-world.md, content/docs/getting-started/io.md, content/docs/getting-started/runtime-model.md, content/docs/getting-started/tasks.md, content/docs/going-deeper/building-runtime.md, content/docs/going-deeper/frames.md, content/docs/going-deeper/futures-mechanics.md, content/docs/going-deeper/returning.md, content/docs/going-deeper/timers.md, content/docs/overview.md, layouts/docs/single.html
The "next" link order in the guides broke with the refresh.
=> Fix "next" link order

config.yaml, content/docs/internals/intro.md, content/docs/internals/net.md, content/docs/internals/runtime-model.md
A guide covering the internals. So far, this covers the runtime module and the network driver (reactor).
Examples need to pass CI still.
=> Internals doc

content/docs/getting-started/io.md, content/docs/getting-started/runtime-model.md
In general `ErrorKind::WouldBlock` is an implementation detail and not super relevant to the topic at hand. It was mentioned twice, once of which I completely removed. The other mention I still left in, but de-emphasized it by moving it into parentheses.
=> Change how and when ErrorKind::WouldBlock is mentioned

content/docs/getting-started/futures.md
This fixes CI by updating the examples to stop using the deprecated API.
=> `ConnectFuture` moved

content/blog/2018-08-async-await.md, content/docs/overview.md
The link to the Hyper example with async/await was broken. This PR corrects that.
=> Fix broken link to async/await with Hyper.

layouts/index.html
The overview page is very easy to miss, and I think users are better off landing there before moving on to hello-world.
=> Change get started link

content/docs/getting-started/hello-world.md
The current hello-world example is fairly complex. It uses Streams and Futures, and it spawns sub-tasks on the runtime from within a combinator. It also uses sockets which might require a bit more background knowledge than files do. I think ultimately the "example" page of the getting started section should be as complex as the current hello-world example. 
The hello world example is now truely minimal. It has two futures and it spawns the parent future on the runtime. It deals with files which everyone should be familiar with.
=> Simplify the hello world Example

content/docs/getting-started/hello-world.md
Hopefully anyone who is trying out the tokio tutorial has worked through *the book* before, but if they haven't and they haven't included crates before, I could imagine not referencing the specific file to be a problem.
=> Be more explicit on how to include crates maybe?

content/docs/getting-started/hello-world.md
The `-p` flag conflicts with the `-l` flag and `nc` exits without binding to a port. 
The correct usage is `nc -l <some_port>`. 
As per the `nc` man pages: 
```
It is an error to use this option in conjunction with the -p, -s, or -z options.
```
=> Remove unnecessary port flag

content/docs/getting-started/futures.md
This tiny PR adds a newline to get a bulleted list to render correctly in the [Streams Section of the Futures page](https://tokio.rs/docs/getting-started/futures/#streams).
=> Add newline so list renders correctly

content/docs/overview.md
Before:
```
wrote (4, ReadHalf { handle: BiLock { inner: Inner { state: 0, inner: Some(UnsafeCell) } } }, WriteHalf { handle: BiLock { inner: Inner { state: 0, inner: Some(UnsafeCell) } } }) bytes
```
After:
```
wrote 4 bytes
```
The latter seems like the intended outcome.
=> Shorten echo example output by skipping debug info

content/docs/futures/combinators.md, content/docs/going-deeper/returning.md, content/docs/going-deeper/runtime-model.md, content/docs/going-deeper/timers.md
This explicitly adds the Send trait to all boxed Future examples, and adds
some language to explain why. Also added another example of when Box is
required (trait definitions). Documentation on `impl Trait` is unfortunately sparse because it's a new feature in Rust, and having to box a return from a trait definition is where I personally ran into problems.
I strongly feel that `+ Send` should be the default for all boxed future examples, because forgetting it leads to serious headaches. (Honestly? We should patch futures to impl Send. But I'm new here.) Generally any example folks might copy-paste from should "just work". The rustdoc says to use `tokio::run` for handling execution in most cases, and by default Send is a requirement there.
=> Clarify Box<Future<...> + Send> (doc-push #87)

content/docs/futures/getting_asynchronous.md
The example provided for "chaining computations" at https://tokio.rs/docs/futures/getting_asynchronous/ wasn't very clear to understand. These changes should increase readability without changing behaviour.
=> Make example in future chaining easier to understand

content/docs/getting-started/hello-world.md
Minor fix, adds link to `Futrues` page in the tutorial/docs.
=> fix (docs): adds url to Futures page from hello-world page

content/blog/2017-03-tokio-io.md, content/blog/2018-02-tokio-reform-shipped.md, content/blog/2018-03-timers.md, content/docs/getting-started/echo.md, content/docs/getting-started/runtime.md, content/docs/going-deeper/building-runtime.md, content/docs/going-deeper/runtime-model.md
Fixes broken links from #251.
Links in [content/blog/2017-03-tokio-io.md](https://github.com/tokio-rs/website/compare/master...vokar97:fix-broken-links?expand=1#diff-a589021cf16a73f77248a6c5a0c762d6) point to specific versions containing required traits, structs and functions, since otherwise the blog post may be hard to understand.
=> Fix broken links (issue #251)

static/css/tokio.css
(The difference is in the navbar.)
=> Fix misaligned logo on mobile

content/docs/getting-started/echo.md, content/docs/getting-started/hello-world.md, content/docs/going-deeper/chat.md
blob/master/examples to blob/master/tokio/examples
=> fix urls to tokio examples

content/blog/2018-03-tokio-runtime.md, content/docs/getting-started/echo.md, content/docs/getting-started/hello-world.md, content/docs/going-deeper/building-runtime.md, content/docs/going-deeper/chat.md, content/docs/io/overview.md, content/docs/overview.md, layouts/index.html
Some links to tokio examples became outdated, fixed it in both docs and blog posts.
=> Update all links to tokio examples directory

content/docs/futures/overview.md
The single bullet in the overview kind of stand out as being very _technical_ compared to the others and it does not clarify the subtleties of the `()`. As a *Rust* _n00b_ I found this confusing, since the abstraction level in the documentation is not consistent.
=> Proposal for minor improvement/clarification to the overview of futures

layouts/index.html
Per title. Alternative: drop "an"
=> Fix a grammatical error

content/docs/getting-started/echo.md
The `futures` crate isn't used in any of the visible portion on the tokio.rs
site, so the extern crate declaration should be commented out from the code
samples.
Also, since the crate is used in the commented out portion of the code, it
should also be added to Cargo.toml, but commented out.
=> Make futures crate usage consistent in echo server

content/docs/futures/spawning.md
In the background processing code example there seem to be 2 misplaced comments.
I removed the one about writing to the socket since it doesn't make sense in this context and moved the drop comment right before `.map(|_| ())` where it should be, as far as I can tell.
Let me know if the first comment should be replaced instead.
=> Rewrite comment in spawning docs

content/docs/futures/combinators.md
The example code was lacking an adapter to changefrom the future type returned by
the chained and_then calls to the future type that is expected by tokio::run.
Fixes: #308
=> Fix example for chaining calls to and_then

content/docs/futures/combinators.md
"trying to conditional return errors" => "trying to conditionally return errors"
"where as" => "whereas"
=> Fix typos in combinators.md

content/blog/2019-08-tracing.md
`outut` => `output`
Hope I guested right :D
=> Fix typo in tracing blogpost

content/blog/2019-11-tokio-0-2.md
This is an attempt to fix a link that is being rendered incorrectly on <https://tokio.rs/blog/2019-11-tokio-0-2/>. The Markdown renders fine on GitHub before and after the change. I didn't check how Hugo renders it after this change, so you will want to do that.
=> Fix Linkerd link

content/docs/getting-started/hello-world.md
I just tested this command and I don't think you use the -p flag with the -l flag. The correct usage is to just specify the port after the -l flag.
=> Fix netcat command

content/blog/2019-11-mio-v0.7-alpha.md, content/blog/2019-12-mio-v0.7-alpha.1.md
This announces Mio 0.7 alpha 1.
There are a number of TODOs left which I'll clean up during the course of the week, I just wanted some feedback. My personal writing style is a bit impersonal and we might want to change that.
/cc some major contributors to the release @carllerche, @PerfectLaugh, @kleimkuhler, @asomers, @FXTi.
P.S. English isn't my first language and I'm (very) dyslexic so there will be grammar/language mistakes :)
=> Add blogpost of Mio 0.7 alpha 1 announcement

content/blog/2019-12-compat.md
This branch adds a blog post announcing the release of `tokio-compat`.
We should make sure to publish the crate first, since I'd like to be
able to link to it on docs.rs and crates.io in the post.
=> blog: add tokio-compat announcement post

content/blog/2019-12-compat.md
The date accidentally said the post was published yesterday, but it went live
today. The old weight would have placed it after the Mio announcement
rather than before. Now they will appear in chronological order.
=> blog: fix date and weight for tokio-compat announcement

content/blog/2019-12-compat.md
This link was missing a reference. This fixes it.
Thanks to @davidbarsky for catching this one!
=> blog: fix links in tokio-compat announcement

content/docs/futures/spawning.md
Tiny typo. `s/parallism/parallelism/`.
=> Fix typo in spawning.md

layouts/index.html
The current link is old and points to a version that predates
async/await. There is no 0.2.x branch that I can see corresponding to
the 0.1.x branch, so I'm proposing pointing to master.
=> Update Example link to point to master.

content/docs/getting-started/hello-world.md
```
$ socat TCP-LISTEN:6142, fork stdout
2020/01/14 09:24:38 socat[52031] E exactly 2 addresses required (there are 3); use option "-h" for help
```
needs to be without a space after the comma -- rrgh!
```
$ socat TCP-LISTEN:6142,fork stdout
```
=> socat fails with space after comma

content/docs/overview.md
if this is controversial, I can put into two PRs...
1) API doc links were pointing to specific version of Tokio, now they point to latest
2) removed echo example here -- it's hard to keep this in sync with [README](https://github.com/tokio-rs/tokio#example) + [echo server tutorial](https://tokio.rs/docs/getting-started/echo/).  I figure one fewer copy of this would make things easier to maintain (and not sure it adds a ton of value here)
Note; there are some key content sections which are out of date, and I've opened those up as a separate issue https://github.com/tokio-rs/website/issues/405, since that might take a bit more time for someone to write
=> fix links, remove duplicate echo example

content/docs/getting-started/hello-world.md
Two of the links in hello world docs are 404ing because they point to wrong URLs and one link is not present. This PR fixes that.
=> Fix links in hello world docs

content/docs/getting-started/runtime.md
Adds an example to `getting-started/runtime.md` regarding the fact that futures must be polled to complete them.
=> Add example about futures that must be polled (runtime.md)

static/css/tokio.css
I was having trouble reading what are categories vs pages within the categories
I think indenting the page titles in the left nav helps a bit.  Added before/after shots below (though ignore the content change which is just that the branch is from a little while ago -- these changes are just the visual layout indent, no content changes).
=> left navigation in documentation: indent subtopics for readability

content/docs/getting-started/cargo-dependencies.md
This prevents an issue for beginners going through the getting started docs where they do not know that they need to call .unwrap() so that a result is not passed into write(). Not doing this will give the following error:
```
error[E0599]: no method named `write` found for type `std::result::Result<tokio::net::tcp::stream::TcpStream, std::io::Error>` in the current scope
let result = stream.write(b"hello world\n").await;
^^^^^ method not found in `std::result::Result<tokio::net::tcp::stream::TcpStream, std::io::Error>`
note: the method `write` exists but the following trait bounds were not satisfied:
`std::result::Result<tokio::net::tcp::stream::TcpStream, std::io::Error> : tokio::io::util::async_write_ext::AsyncWriteExt`
```
=> docs: add unwrap to prevent passing Result to write

content/docs/getting-started/echo.md
fixes https://github.com/tokio-rs/website/issues/369
I just removed the part that refers to `for_each` since now the code uses `next` 
better to describe in the text or API docs if anyone wants to go into detail about that
=> remove stale comment

content/blog/2020-04-preemption.md, layouts/partials/header.html
Rendered: https://deploy-preview-422--tokio.netlify.com/blog/2020-04-preemption/
=> blog: reducing tail latencies with auto yielding

components/layout.tsx, public/favicon.svg
This adds an SVG favicon using the existing Tokio logo here: https://github.com/tokio-rs/website/blob/master/public/img/icons/tokio.svg. It's resized and supports dark mode (using CSS media query). Website falls back on the PNG favicon if the browser doesn't support SVG.
Tested against Chrome, Firefox, and Safari on macOS.
Currently, the PNG favicon does not support dark mode. Ideally, this favicon should be modified to work on either light or dark mode. Something to consider in the future.
=> Adds SVG favicon

content/tokio/tutorial/shared-state.md, content/tokio/tutorial/spawning.md
It doesn't make sense to run `cargo install` after adding the `bytes` dependency.
=> Fix typos in tutorial

tutorial-code/spawning/src/main.rs
I was working through the tutorial and noticed a difference in my code, and the code linked at the bottom of the 'spawning' page.  I assume the diff is unintentional - here's a little PR to make align the text of the tutorial and the source code in tutorial-code/
=> Update spawning tutorial-code to match tutorial content.

content/tokio/tutorial/streams.md
Also add rust syntax highlighting to markdown fence of example.
Fixes #467.
=> Fix: Missing decrement in Interval stream example

components/layout.tsx
#430 used a relative path to the favicon. This always fetches the favicon from the root.
=> Fixes favicon path

styles/styles.scss
=> make li list-style-type and li::before content formatting exclusive to ul li

content/tokio/tutorial/async.md
The first time `std::sync::Mutex` is being imported and used during
`MiniTokio` exercise it's not explicit. Although Mutex is a well know
struct from the default sync lib, for a tutorial it makes more sense to
make it clear and avoid confusion. `std::sync::Arc` is also being silently
imported, but it was already used previously.
This commit makes the `std::sync::{Arc, Mutex}` import visible on the docs
removing the comment signal `#`.
When following the tutorial [Async in depth][0] part, the resulted code is
missing some changes for a working code. It does not compile as the
`MiniTokio::new()` and `MiniTokio::spawn()` methods are not adjusted to
reflect the change from `VecDeque` to `crossbeam::channel`s.
This commit adds the missing changes and creates explanations for the added
code as …
=> Async in depth tutorial improvements

content/tokio/tutorial/channels.md
Fix a minor typo:
Many values can be send. => Many values can be sent.
=> Minor typo in channels.md

content/tokio/tutorial/channels.md
First off, I want to say thank you all for writing the excellent tutorials for Tokio. I didn't realize they existed until I was reading about the 1.0 release. I have struggled a bit with Rust in more complex projects, and adding Tokio's asynchronous fanciness on top of that has always seemed a bit daunting. These tutorials do an excellent job demystifying the project and getting me excited to use it.
While walking through the tutorial, I saw warnings while following along with the code snippets. The sample snippets suggested making a couple of variables mutable that the compiler said didn't need to be. They are not mutable in [the final checked-in code sample](https://github.com/tokio-rs/website/blob/master/tutorial-code/channels/src/main.rs#L25-L27), either.
I was worried that they might …
=> Remove mut in tutorial variables that cause warnings

content/tokio/tutorial/framing.md
The code snippet provided in the guide appears to be a hybrid of the `write_frame` and `write_value` functions in the "final" code in https://github.com/tokio-rs/mini-redis/blob/tutorial/src/connection.rs#L159-L184.
I was initially confused why the sentence preceding the snippet mentioned `write_frame` but the code in the snippet is for a function called `write_value`. The provided snippet is *more* similar to the `write_value` function in the final code, but since it's purpose in the guide is to actually write a frame, `write_frame` seems like a clearer name for this specific snippet.
=> Clarify function name in "framing" guide

content/tokio/tutorial/streams.md
Thank you for a great tutorial.
I found a couple of dead links in the "Streams" tutorial chapter.
And I fixed it.
Could you review it?
=> Fix a couple of dead links in "Streams" tutorial chapter

content/tokio/tutorial/async.md
Hello, I noticed that the mini tokio tutorial code didn't work unless I added a `use futures::task::self;` statement. It looks like `task::self` is included in the code snippet, but it's commented out and doesn't render on the site itself. 
This PR adds the necessary import statement in one possible place, namely the `impl ArcWake for Task` block. The statement could alternatively be added in the `impl MiniTokio` block a bit further down.
=> Import futures::task::self in async chapter

content/tokio/tutorial/channels.md, content/tokio/tutorial/hello-tokio.md, content/tokio/tutorial/shared-state.md, content/tokio/tutorial/spawning.md
While reading the tutorial, I found several points to be fixed. So, this PR consists of:
- updates link URLs to crates' documentation
- fixes typo
- adds dollar signs before shell commands for consistency with the other examples
=> Fix link URLs and typo in tutorial

content/tokio/tutorial/io.md
Currently the link to the `copy` version of echo server seems wrong. If people click this link, they are brought to the `manual` example. So in this PR I've fixed it.
In addition, also fixed a typo :)
=> Fix link URL and typo in tutorial

content/tokio/tutorial/index.md
I'm going through tokio's tutorial and thought it'd be better to specify that the reader must open a new terminal window to try the `$ mini-redis-cli get foo` command. Let me know what you guys think :)
=> Specify that two terminal windows are required

content/tokio/tutorial/framing.md
Currently, `Bytes` is linked to https://docs.rs/bytes/ unintentionally. (it should be linked to https://docs.rs/bytes/1/bytes/struct.Bytes.html)
According to [the CommonMark spec](https://spec.commonmark.org/0.29/#example-174), link references are supposed to be case-insensitive, but there is another `bytes` reference in the "framing" page. Therefore, `Bytes` and `bytes` are conflicting.
This PR changes the way `Bytes` is referenced to fix the issue. Also changes `BytesMut` for consistency.
=> Fix link references in "framing" chapter

content/tokio/tutorial/hello-tokio.md
The `cargo install` command did not refer to the actual crate name.
=> tutorial: Fix crate name for mini-redis

content/tokio/tutorial/async.md, doc-test/Cargo.toml, tutorial-code/mini-tokio/Cargo.toml
I noticed the version of crossbeam to be outdated. This just upgrades crossbeam to 0.8.0.
=> Upgrade crossbeam to 0.8.0

content/tokio/tutorial/hello-tokio.md, tutorial-code/hello-tokio/Cargo.toml, tutorial-code/hello-tokio/src/main.rs
Reverts #550.
Closes #553.
It is too early to introduce the `bytes` crate on the Hello Tokio page. Using `.into()` allows us to avoid doing that on this page.
=> Revert ".into -> Bytes::from"

content/tokio/tutorial/select.md
Reading the "select" chapter in the tutorial, I was puzzled a bit by the description that says `Future` is a trait that must be implemented by a value in order to call `.await` on it, because the previous chapter "Async in depth" already covers that fact. So I attempted to fix it.
Besides, fixed a tiny typo as well.
=> Fix select chapter in tutorial

content/tokio/tutorial/channels.md, content/tokio/tutorial/framing.md, content/tokio/tutorial/io.md
When following the tutorial I noticed some slight grammar mistakes, for instance a missing `the`.
Just don't merge yet, I'm not finished with the tutorial!
I am open to suggestions if you wish me to review more text or if you think my corrections are pointless / counterproductive.
- [  ] read the entire tutorial to review the whole text.
=> Minor grammar fixes

content/tokio/tutorial/channels.md, content/tokio/tutorial/io.md
As discussed in #503 , the tutorial becomes confusing around the Channel section. I have idenitfied it as a lack of instructions on structuring the code.
Following the pattern of instructions of the Spawning page (create an `examples/` directory, rename `main.rs` into it), I have edited the tutorial so it suggests to rename / create binary files in a `bin` directory: 
- `src/bin/server.rs`
- `src/bin/client.rs`
- `src/bin/echo-server-copy.rs`
- `src/bin/echo-server.rs`
With all the additional run instructions: `cargo run --bin …` and some verbosity.
I believe this will help learners like me who like to type code and tend to be reassured when told where and how.
=> Add cargo commands to the tutorial

content/tokio/tutorial/streams.md
Just a small grammatical change.
=> Fixed the tense of a use of `pin`

content/tokio/tutorial/io.md
Going to the tutorial I noticed this warning
```
warning: variable does not need to be mutable
--> src\bin\echo-server.rs:6:9
|
6 |     let mut listener = TcpListener::bind("127.0.0.1:6142").await.unwrap();
|         ----^^^^^^^^
|         |
|         help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
```
=> Remove unneeded mutability on TcpListener

components/social-links.tsx
This commit makes the social links open up on a new tag instead of replacing the website tab
=> Open up social links in new tab

content/blog/2021-05-14-inventing-the-service-trait.md
I've been writing a guide for the `Service` trait over in [tower](https://github.com/tower-rs/tower/pull/585). @LucioFranco suggested publishing it as a blog post to increase reach. I think thats a great idea 😊
Once this is merged I'll update tower to instead link to this post.
[Rendered 🖼](https://deploy-preview-570--tokio.netlify.app/blog/2021-05-14-inventing-the-service-trait)
=> blog: add "Inventing the Service trait" tower guide

components/content.tsx, components/menu.jsx, lib/blog.js, next.config.js, pages/blog.jsx, pages/blog/[...slug].jsx, styles/styles.scss
This adds a new blog index at `/blog`. It lists all blog posts for all years.
A new link is added to the blog post page sidebar. Only the 6 most recent posts are shown in the sidebar.
I added a new `blog.js` module to encapsulate this logic, and pulled out most of the related code in `[...slug].js`.
I also added a fix for the "fs module not found" error that was popping up without related changes. This might be specific to my environment, and I can take that out if it's not wanted or too unrelated.
=> Show fewer blogs in sidebar and link to an index

components/menu.jsx, pages/blog.jsx, styles/styles.scss
@davidpdrsn caught that #584 looked incorrect on mobile. My bad, I should have tested that out.
This fixes the styling on mobile by making the index full-width and only showing the "All Posts" link when the TOC is expanded.
=> fix blog index and link on mobile

components/content.tsx
Fixes #586.
Only shows the "More Blog Posts" link if the current route begins with `/blog`.
=> only show "More Blog Posts" on blog routes

components/footer.tsx, styles/styles.scss
This is required to be on the OSS plan, but we lost the link in the redesign.
=> add netlify link in footer

content/blog/2021-07-announcing-axum.md
[`axum`](https://github.com/tokio-rs/axum) is a little web framework that I've been working on for the last few months. Been chatting with @carllerche about it.
The idea is something simple that integrates well with tower, tower-http, and is based on hyper and tokio. We don't feel that space is well served by any existing framework.
Some links for those interested:
Repo: https://github.com/tokio-rs/axum
Crates.io: https://crates.io/crates/axum
Docs: https://docs.rs/axum
There are also [examples in the repo](https://github.com/tokio-rs/axum/tree/main/examples) that show some slightly larger apps.
=> blog: announcing axum

content/blog/2021-07-announcing-axum.md
I suppose this is why its not showing up on [tokio.rs](https://tokio.rs/blog) yet.
=> blog: fix dates of axum announcement

.github/workflows/ci.yml
Update version of Rust in CI to avoid running in to https://github.com/hawkw/sharded-slab/issues/60 in CI.
=> chore: update Rust version in CI

content/tokio/tutorial/index.md
Not to is a split infinitive and is historically frowned upon. This simple change improves readability greatly (source: it's 12 in the morning)
=> To not -> Not to

content/tokio/tutorial/index.md
This url was changed in #590. The link still works because I added a redirect, but we should prefer the direct link.
=> Don't use old link for bridging article

components/hero.tsx
Closes #437.
Alternative solution is to remove `has-text-left-mobile` instead of change in the pr. 
https://github.com/tokio-rs/website/blob/1d940c88f160c2fe0d657a6e43e10a406eb25a89/components/hero.tsx#L25
How it looks with only button centered.
How it looks with entire container centered on mobile.
I've found everything centered a bit harder to read so I didn't include it. But if entire container centered looks better I'll change it.
=> Center `Getting Started` button on landing page

content/tokio/tutorial/io.md
I think file is more reasonable name in this case.
=> Rename buffer to file in write_all example

content/blog/2021-12-announcing-tokio-console.md
Currently, the table of contents for the console blog post looks kind
of weird: "thanks to" is a subsection of "roadmap", and "announcing
tokio-console 0.1" appears twice, once for the post title and once
for the markdown H1 at the top of the post.
This PR fixes these cosmetic issues. I made "thanks to" an H1 header so
it isn't a subsection of the "roadmap" section, and removed the
duplicate title. I also added a section header for how to get started
using the console.
=> blog: fix up headers in console blog post

content/tokio/tutorial/spawning.md
I am a newcomer to rust and hadn't learned what `'static` meant. Adding the word 'lifetime' would help clarify the keyword for anyone else in my position.
=> Update language in spawning tutorial

content/tokio/tutorial/io.md
Clarifies that the next code block relates to the server and not client that was
just mentioned previously.
=> Update io.md, minor clarification

content/tokio/tutorial/select.md
error[E0277]: `()` doesn't implement `std::fmt::Display`.
We use the display of the Debug trait instead.
=> Update select.md, fix example error

content/tokio/tutorial/select.md
This was something small I noticed when reading through the tutorial: "a" was repeated.
=> tutorial: Fix a typo in select.md

content/blog/2021-05-14-inventing-the-service-trait.md
At this point in the tutorial the handler is just `F: Fn(HttpRequest) -> HttpResponse` so we can't `.await` it.
=> Remove `await` from non-async function call

content/tokio/topics/tracing-next-steps.md
A few fixes for this new documentation page: https://tokio.rs/tokio/topics/tracing-next-steps (which was introduced in #654).
=> fix(tracing-next-steps): a few typos

content/tokio/tutorial/shared-state.md
The "Update process()" section mentions that we indeed need to pass the `HashMap` as an argument. As I was going through those changes, the change from `Vec<u8>` to `Bytes` went under my radar (needs a change in line 138), and although it's simple enough to detect, I thought it would make sense to include this short explanation.
Ran the indicated tests in the README.md locally:
```
cargo +nightly test
cargo test --all
```
Do notice that the doc tests required me to run with `RUSTFLAGS="--cfg tokio_unstable"`, I can update the README as well to reflect this change if that's OK.
=> Added a small explanation of a change to Bytes

README.md
As explained in a previous [PR](https://github.com/tokio-rs/website/pull/666), when running
```bash
cargo +nightly test
```
The tests failed because a doc-test needs `tokio-unstable`. I added this flag in the instructions, and add what felt to me like a better explanation of how to set up the local server.
Followed the testing instructions again.
Markdown in my IDE looked pretty for the doc changes.
=> Minor tweaks in the README to explain setting up the server and running tests

content/blog/2022-10-announcing-async-backtrace.md
Announcement post for initial release of async-backtrace crate.
@carllerche
=> blog: announce async-backtrace

content/tokio/tutorial/channels.md
This brings the tutorial code to the state of the linked code.
It might be nicer to use `hello` as the key and `world` as the value as in the earlier tutorials though.
=> Fix query key in channels tutorial

content/tokio/tutorial/streams.md
The implemented Stream yields `()` any number of times (as specified by the `rem` field), not three times.
=> Correct a statement introducing the Stream implementation

content/tokio/topics/tracing.md
> Unless overriden, a span with the [INFO](https://docs.rs/tracing/latest/tracing/struct.Level.html#associatedconstant.INFO) [level](https://docs.rs/tracing/latest/tracing/struct.Level.html) will be generated. The generated span’s name will be the name of the function. By default, all arguments to the function are included as fields on the span. Arguments that are tracing [primitive types](https://docs.rs/tracing/latest/tracing/field/trait.Value.html#foreign-impls) implementing the [Value trait](https://docs.rs/tracing/latest/tracing/field/trait.Value.html.) will be recorded as fields of that type. Types which do not implement Value will be recorded using [std::fmt::Debug](https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html).
See: [docs on …
=> fix(blog): update default instrument level to `info`

content/tokio/tutorial/framing.md
It was not clear (to me) when I was following the tutorial that I was supposed to create a new `connection.rs` file to add the code for the connection struct. Hopefully this will make it clearer.
=> added instructions to create a new file connection.rs

content/tokio/tutorial/spawning.md
This commit removes an extraneous pipe character, as well as inserts a newline between distinct two thoughts for better readability.
Before this change, the paragraph looked like this:
Notice the extraneous pipe (`|`) character. After this change, it looks like:
=> Remove extraneous pipe character within info block in spawning.md

content/tokio/topics/shutdown.md
Cancellation Tokens should be used to notify task to shut down instead of broadcast channels. Therefore, I replaced usage of Broadcast Channel in [Telling things to shut down section](https://tokio.rs/tokio/topics/shutdown#telling-things-to-shut-down) of Graceful Shutdown topic docs with Cancellation Tokens
closes #694
=> Added cancellation-token content in Graceful Shutdown topic docs

styles/styles.scss
Found this a little annoying that on my 13'' MacBook vertical menu overflows and it's impossible to scroll it until the end of the page.
So I made the container sticky (instead of nested `aside` element) and overflow-able with scroll. Also rearranged paddings so that they are on container level too, I think it's slightly better for how the page feels.
=> Fix side navigation menu overflowing on narrow screens

content/tokio/tutorial/hello-tokio.md
The Line 1 and Line 2 conveys the same idea of using full feature flag for this tutorial. Line 1. When depending on Tokio for this tutorial, the `full` feature flag is enabled. Line 2. For now, use the "full" feature when depending on Tokio.
=> Dropping repetitive text

content/blog/2019-10-scheduler.md
Hi everyone,
While reading through the blog, came across this typo
=> fix typo `though` -> `thought`

content/tokio/topics/index.md
**PR Summary**:
PR contains a small fix to link that should point to the "tracing next steps" (instead of "tokio next steps").
=> fix: link to tracing next steps page

content/tokio/tutorial/shared-state.md
Lately the std mutex has perfectly fine performance comparable to parking_lot and unlike parking_lot, has lock poisoning. Thus it seems more reasonable to not explicitly recommend it, and if people have one of the specialized use cases where lock choice is super important, they probably know that.
See also: https://hachyderm.io/@rain/110738343644683050
=> Remove suggestion for parking_lot mutexes

content/tokio/tutorial/async.md
It's a little bit confusing for a newcomer that notify one method is called on notify two -- it gives wrong hint/intuition to some readers, so it worth to choose a name which won't suggest such semantic, which isn't there.
Looks like this part of code is only in tutorial text, and nothing to sync in the supplementary code.
=> Clarify variable naming in async.md

content/tokio/tutorial/index.md
There are great resources around, and the tutorial could be the first contact point for many people with Tokio. 
Why not link them? I think practical examples increase the overall value of the tutorial.
=> Tutorial: Add link to rayon example

content/tokio/topics/shutdown.md
As discussed :) the docs on the topic pages were not reflecting the new task tracker from tokio_util.
The previous approach was moving mpsc::Senders to tasks and dropping them when finished, thereby notifying the main task which awaits on the mpsc::Receiver.
This PR changes the example to use a Task Tracker instead.
=> Update docs on terminating groups of tasks

content/tokio/glossary.md, content/tokio/topics/bridging.md, content/tokio/topics/shutdown.md, content/tokio/topics/tracing-next-steps.md, content/tokio/topics/tracing.md, content/tokio/tutorial/channels.md, content/tokio/tutorial/hello-tokio.md, content/tokio/tutorial/select.md, content/tokio/tutorial/shared-state.md, content/tokio/tutorial/streams.md
IMHO, the markdown in this repo should be formatted and relatively free of lints, because that lowers the barrier of entry for contributions. Let me know what you think :)
=> Apply markdown lint and formatting

content/blog/2023-11-23-announcing-axum-0-7-0.md
[0.7 is almost ready 🚀](https://github.com/tokio-rs/axum/milestone/6)
[🖼️ Rendered](https://github.com/tokio-rs/website/blob/david/axum-0-7/content/blog/2023-11-23-announcing-axum-0-7-0.md)
=> blog: announcing axum 0.7.0

content/tokio/topics/shutdown.md
The text was wrapped with square brackets, I assume the original author intended to add a link but forgot. This PR introduces the link.
=> Add link to mpsc in the shutdown docs

content/tokio/topics/testing.md, lib/markdown.js
`# if true { return }` is shown in the code block of the topic page [Unit Testing](https://tokio.rs/tokio/topics/testing):
Based on https://github.com/tokio-rs/website/pull/735, `# if true { return }` was used to let doc tests pass.
The original function to remove `#` lines does not cover all cases.
This PR fixes that function to match [what librustdoc does](https://github.com/rust-lang/rust/blob/0ecbd0605770f45c9151715e66ba2b3cae367fcb/src/librustdoc/html/markdown.rs#L170).
Another forgotten `#` on the same page:
Also in blog [New Timer implementation](https://tokio.rs/blog/2018-03-timers):
These `#` lines will be removed by the fixed function.
=> fix: `# if true { return }` is not hidden in html code block

content/tokio/tutorial/async.md
Updates the tutorial to handle spurious wakeups. Continuation from discussion in https://github.com/tokio-rs/website/pull/739
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=60eef8a9311ff77e8d9e0ec0dd935dee)
=> Handle spurious wakeups

content/tokio/tutorial/channels.md
`tx.send()` returns a `Result` which must be used otherwise the compiler produces warnings.
=> Add missing `unwrap()`s

.github/workflows/ci.yml, components/content.tsx, components/footer.tsx, lib/markdown.js, package.json, pages/[...slug].jsx, pages/blog/[...slug].jsx, styles/styles.scss
This patch adds a small GitHub actions job for verifying that the code style conforms with the prettier configuration.
I have also ran prettier locally to fix up the files that didn't conform with the code style prior to this patch.
Let me know what you think. I know this isn't all that important, but it bothered me that code unrelated to my changes would re-format in my editor.
=> Add GitHub actions step for validating prettier code style

content/tokio/tutorial/channels.md
`Clone` of `watch::Sender` was introduced in https://github.com/tokio-rs/tokio/pull/6388, and that change was shipped in the [latest v1.37.0 release](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.37.0).
So I fixed the document
=> Fixed watch

content/tokio/tutorial/channels.md
Both 'queing' and 'queueing' are correct, but for consistency's sake should stick to 'queing'.
=> Queing spelling change in channels.md

content/blog/2023-11-27-announcing-axum-0-7-0.md
The subject "high level utilities" is plural, so the verb should be "have" instead of "has."
=> Fix grammar 2023-11-27-announcing-axum-0-7-0.md

content/tokio/tutorial/shared-state.md
- Moved Tasks, threads and contention to the end:
- This is deeper and more detailed than the previous sections
- Also, the part on restructuring the code should be higher up
- Added more warnings on Send Guards.
- Linking to Alice Ryhl's post twice, both segments seem to benefit from this link.
This PR has some "quick fixes", that I believe would be helpful for tokio users at large.
The best thing we could do I believe, however, would be to sanitize the examples, so that all the example code would have wrapped mutexes only, making it much less likely for tokio users to end up with problematic code.
=> Some edits for Tutorial: Shared State

styles/styles.scss
Hi,
When I was browsing the website, I found unnecessary horizontal scroll bars under each of the code blocks, which kind of affect visual consistency, as the following image shows:
Then I went to the `styles.scss` file and found the attribute `overflow-x` was set to `scroll`. This means the horizontal scroll bar will always be there, whether the content is overflowing on the x-axis or not. I changed the value to `auto` to hide the bar when no overflow happens but show the scroll bar when horizontal scrolling is necessary. 
The result after this modification is as shown in the following images:
When no x-scrolling needed:
When content overflows:
Thanks so much for considering this update!
=> Corrected overflow-x style to remove unnecessary horizontal scroll bar

.github/workflows/ci.yml, rust-toolchain.toml
Fixes running doc-test locally
=> pin toolchain version to 1.81

.github/workflows/ci.yml, .mise.toml, netlify.toml
This is the current LTS version which is recommended for prod usage.
Updates the netlify config and adds a mise.toml config file to configure
the node.js version to use when running the site locally.
This will fix the problem running next.js in https://github.com/tokio-rs/website/pull/778
=> use node.js 20.18.0

content/blog/2021-05-14-inventing-the-service-trait.md
Reading this great article, saw this missing apostrophe. I'm pretty sure it's supposed to read "...but why _that is_ necessary..." (emphasis added).
Thank you for all of the great work you folks do! Open source maintainers don't get enough :heart: 
- Nick
=> Add a missing apostrophe in "Inventing the Service Trait"

content/blog/2024-10-23-announcing-toasty.md
Noticed a minor typo while reading this article. Did the edit on phone and don't know how the `div` on line 208 differs and how that got into the diff.
=> Fix DynamoDB typo in Toasty blog post

content/blog/2022-08-whats-new-in-axum-0-6-0-rc1.md
The links for those elements are missing in the blog post
=> axum 0-6-0-rc1 - add links to rc releases

content/blog/2025-01-01-announcing-axum-0-8-0.md, styles/styles.scss
=> Add "Announcing axum 0.8.0" blog post

content/tokio/tutorial/spawning.md
Based on https://github.com/tokio-rs/tokio/issues/7423, the spawning tutorial has the user running both the Redis server and client in separate terminal windows. Let's disambiguate which terminal window the user should be expecting output from.
Fixes: https://github.com/tokio-rs/tokio/issues/7423
=> Disambiguate client-server references in Spawning tutorial
