content/blog/tokio-0-1.md
one typo, one area where i think that the current wording is a bit confusing
=> typo and small grammar fix

content/docs/going-deeper/third-party.md
Thrussh is an SSH client and server library. The API has been tested with other protocols like postgres, using asynchronous callbacks spawn in the same event loop.
Tokio is awesome! Thanks a lot!
=> Thrussh is completely based on tokio since 0.8

content/docs/going-deeper/third-party.md
Just fixing a small typo/missing word.
=> Fixing typo in third-party.md

content/docs/getting-started/tls.md, content/docs/going-deeper/architecture.md, content/docs/going-deeper/multiplex.md
Fixing a couple of more typos.
=> Fixing typos

content/docs/getting-started/core.md, content/docs/getting-started/reactor.md, content/docs/getting-started/tls.md, content/docs/going-deeper/architecture.md, content/docs/going-deeper/multiplex.md, content/docs/going-deeper/returning.md
Various things I came across while reading the docs
=> Various sundry typos and whatnot

static/css/tokio.css
This includes changes to the header, the main section of the homepage,
and the jumbotron section in order to better accommodate mobile browsers
Addresses #11 in a few ways
=> fix(styles): changes to accommodate mobile

content/docs/getting-started/simple-server.md
It was a little ambiguous where to do the replacement before.
=> Clarify where to replace Echo with EchoRev

ci/test.sh, content/blog/tokio-io.md, content/docs/getting-started/core.md, content/docs/getting-started/futures.md, content/docs/getting-started/pipeline-server.md, content/docs/getting-started/reactor.md, content/docs/getting-started/simple-server.md, content/docs/getting-started/streams-and-sinks.md, content/docs/getting-started/tls.md, content/docs/going-deeper/architecture.md, content/docs/going-deeper/core-low-level.md, content/docs/going-deeper/handshake.md, content/docs/going-deeper/multiplex.md, content/docs/going-deeper/streaming.md, content/docs/going-deeper/transports.md, layouts/index.html, layouts/partials/header.html
At the same time also update the necessary content on the website for the advent of the tokio-io crate
=> Add a tokio-io announcement blog post

content/docs/getting-started/tokio.md, layouts/docs/single.html
=> Add links to reference documentation

content/docs/getting-started/simple-server.md
https://github.com/tokio-rs/tokio/issues/7
=> Fill in LineCodec implementation in example

content/docs/getting-started/pipeline-server.md, content/docs/going-deeper-tokio/handshake.md
Previous pull request was done in Github Web UI and I
not expected that the problem is spanning multiple examples
=> Fill in LineCodec implementation in more examples

content/docs/getting-started/simple-server.md
I found where to put the stateful bits of a server a bit confusing going through the Tokio docs that first time. i think a hint like this would have set me in a better direction
=> Guidance on where to put state and configuration

layouts/partials/footer.html, layouts/partials/header.html, static/css/tokio.css
Todo list:
Screenshots top menu pushes down:
cc @carllerche
=> [WIP]Make a site mobile friendly

content/docs/going-deeper-tokio/third-party.md
Followup to https://github.com/tokio-rs/website/pull/95
=> Fix broken tokio-serial link.

content/docs/getting-started/db.md
Reference:
https://github.com/alexcrichton/futures-rs/pull/556
=> Remove deprecated BoxFuture and boxed from DB example

content/docs/going-deeper-tokio/core-low-level.md
Closes https://github.com/tokio-rs/website/issues/80
=> Fix broken tasks link

content/docs/getting-started/core.md
I think this helps in conveying the message a bit more clearly.
=> Changed the wordings a bit

content/docs/getting-started/simple-server.md, content/docs/going-deeper-tokio/multiplex.md, content/docs/going-deeper-tokio/streaming.md
=> Insert "of" into "a number different services"

content/docs/getting-started/hello-world.md
=> Typo comabinator

content/docs/getting-started/chat.md, content/docs/getting-started/hello-world.md
Signed-off-by: Khaled Karam <khaledkbadr@outlook.com>
=> Fix stream link in chat and hello-world

content/docs/getting-started/runtime-model.md
=> Fix a typo in runtime-model.md

content/docs/getting-started/chat.md, content/docs/getting-started/hello-world.md, content/docs/getting-started/runtime-model.md, content/docs/getting-started/tasks.md
Signed-off-by: Khaled Karam <khaledkbadr@outlook.com>
=> fix Future trait url

config.toml, content/docs/getting-started/hello-world.md, content/docs/getting-started/io.md
Signed-off-by: Khaled Karam <khaledkbadr@outlook.com>
=> fix hello world example url and io links

content/docs/going-deeper/timers.md
very nice examples, but this sentence I had to read 3 times to understand
=> ease reading of sentence

content/docs/going-deeper/frames.md
[Rendered](https://github.com/sbstp/website/blob/frames/content/docs/going-deeper/frames.md)
This is a first draft of docs for framed streams and codecs.
=> Add documentation on framed streams & codecs

content/docs/getting-started/chat.md, content/docs/getting-started/runtime-model.md, content/docs/getting-started/tasks.md
When I was reading through the Getting Started guide, there were a few
spots where I was a bit confused or felt the wording could be improved.
These are a few suggestions that I think would have helped.
=> Suggested improvements for the Getting Started guide

content/docs/getting-started/chat.md
=> Fix a typo

content/docs/getting-started/hello-world.md
Minor spelling error. Hope it's not too small of a contribution!
=> Fix spelling of asynchrous

content/docs/going-deeper/frames.md
=> Fix issue with having deprecated code in codec section of guide.

layouts/partials/header.html, static/css/tokio.css
@krircc I added the link to the translation here. I tweaked the styling a bit. A also filed #206 to track importing the content into the repo and use hugo's translation feature.
Hopefully you will be able to keep the website up to date 👍 
Closes #198, #194
=> Add tokio-zh translation link

content/blog/2018-10-doc-blitz.md
[rendered(ish)](https://github.com/tokio-rs/website/blob/doc-blitz/content/blog/2018-10-doc-blitz.md)
=> Doc blitz blog post

content/docs/getting-started/hello-world.md
- [`Streams`] => [`Stream`]
- add a period sign
=> fix typos in hello-world.md

content/docs/overview.md
fixes https://github.com/tokio-rs/doc-push/issues/68
=> Fixed broken link, include ecosystem reference

content/docs/getting-started/hello-world.md
- Specify `Cargo.toml` for dependencies
- Include explanations of `tokio::{io,net}`
- Add section explaining how to run the code
=> Smaller additions to the hello_world example

content/docs/getting-started/runtime.md
I think this is how was intended to look like.
=> Remove extra # in stream example

content/docs/getting-started/echo.md
As discussed in #250.
cc @rylev
=> Properly comment hack in echo example

content/docs/futures/basic.md, content/docs/futures/overview.md, content/docs/getting-started/futures.md, content/docs/getting-started/hello-world.md, content/docs/overview.md
=> Adopt many of @nrc's proposed changes

ci/test.sh, content/docs/internals/runtime-model.md
=> Switch CI and examples to Rust 2018

content/docs/futures/getting_asynchronous.md
=> Getting Asynchronous section has invalid example

content/docs/overview.md
The usual phrase is "in and of itself" but I think "which is itself very fast" is good here.
=> Minor rewording

content/docs/io/reading_writing_data.md
In content/docs/io/reading_writing_data.md: bites -> bytes
=> Fixed typo

content/docs/futures/combinators.md
I don't think we wanted to spawn only 1 future.
=> Fix a small typo

content/docs/futures/getting_asynchronous.md
Removed extra word from existing comments that seemed to be an error.
=> Corrected minor comment sentence error

content/docs/overview.md
More examples can be found here is now updated to follow new tokio repository structure
=> Fix broken examples link

content/docs/futures/streams.md
Based on https://github.com/tokio-rs/doc-push/issues/96
=> Example of fibonacci stream with 1 second wait using combinators

content/docs/futures/runtime-model.md
This content about streams is already here: https://github.com/tokio-rs/website/blob/master/content/docs/futures/streams.md
=> Remove wrong content about streams

content/blog/2018-03-tokio-runtime.md, content/docs/getting-started/echo.md, content/docs/getting-started/hello-world.md, content/docs/going-deeper/building-runtime.md, content/docs/going-deeper/chat.md, content/docs/io/overview.md, content/docs/overview.md, layouts/index.html
Hi,
I updated to broken example links to point v0.1.x.
Best
Johannes
PS: my first pull, not sure whether I should include the open issues here ;)
=> fixed links to examples

content/blog/2019-08-alphas.md
=> write blog post for release

content/blog/2019-08-tracing.md
This is a rough draft of a blog post introducing the tracing crate. It would be great to get some feedback prior to publishing.
=> rough draft of a tracing blog post

content/blog/2019-08-tracing.md
=> fix typos in tracing blog post

content/blog/2019-10-scheduler.md
https://news.ycombinator.com/item?id=21250189
=> add author name

content/blog/2019-10-scheduler.md
Feel free to cherry-pick the commits you feel are correct.
=> Scheduler blog fixes

content/docs/getting-started/echo.md
This should be merged after #357 lands
=> Update echo doc page

content/docs/getting-started/echo.md
=> Fix echo server examples and prose

content/docs/internals/net.md
Hugo rendered those 2 items as one line.
=> Add extra whitespace

content/docs/getting-started/echo.md
The echo example has a few mistakes that result in code not compiling if stiched together by copy-pasting from the page.
This commit fixes these mistakes and rewords a few sections.
=> Improve echo example

content/docs/getting-started/futures.md
* Clarified first sentence in paragraph
* Fixed typo
=> Fix typo in futures.md

content/blog/2019-12-compat.md
markdown parser does not work nicely with html
=> blog: fixup author links

layouts/index.html
Since Netlify has generously given the Tokio organization a pro plan, I'm adding the credit to the main https://tokio.rs website.
=> Credit Netlify for OSS plan

components/stack.tsx
=> wording (proposal)

content/tokio/tutorial/async.md, content/tokio/tutorial/channels.md, content/tokio/tutorial/framing.md, content/tokio/tutorial/hello-tokio.md, content/tokio/tutorial/select.md, content/tokio/tutorial/shared-state.md, content/tokio/tutorial/spawning.md, content/tokio/tutorial/streams.md
Hey, I really like the new tutorial👍
I fixed some minor typing errors that I have encountered.
=> Fixed minor typing errors

components/libs.tsx
Hi,
Following the suggestion in https://www.reddit.com/r/rust/comments/hvalrb/tokio_new_website_new_guides/fysrvnp/
=> Wording change: replaced "removes" by "reduces"

content/tokio/tutorial/index.md
=> Tiny fix for index.md

content/tokio/tutorial/select.md
=> fix link to Async in Depth

content/tokio/glossary.md, content/tokio/tutorial/channels.md
=> Update channel descriptions

components/layout.tsx, netlify.toml, next.config.js, package-lock.json, package.json, scripts/generate-rss-feed.js
=> add rss feed generation and link on the website

content/blog/2019-08-tracing.md
=> Fix the example link

content/blog/2019-08-tracing.md
=> Update 2019-08-tracing.md to remove duplicate

content/tokio/tutorial/channels.md, content/tokio/tutorial/shared-state.md, content/tokio/tutorial/spawning.md, tutorial-code/shared-state/src/main.rs
This PR improves various things around in the tutorial.
=> Various changes

content/tokio/tutorial/async.md, content/tokio/tutorial/channels.md, content/tokio/tutorial/framing.md, content/tokio/tutorial/hello-tokio.md, content/tokio/tutorial/index.md, content/tokio/tutorial/io.md, content/tokio/tutorial/shared-state.md, content/tokio/tutorial/spawning.md, content/tokio/tutorial/streams.md
Minor fixes, mostly typos, some broken links, and some consistency.
=> Tutorial fixes

content/tokio/tutorial/shared-state.md
It makes more sense to spawn a new task here to remain in the continuity of the previous section!
=> Missing task spawning in Shared state section

tutorial-code/shared-state/src/main.rs
=> Add missing spawn to shared-state

content/tokio/tutorial/spawning.md
Closes  #518
cc @pnkfelix
Honestly I'm pretty unhappy with the terminology used in the link. Maybe we should just take it out and explain it entirely ourselves?
=> Elaborate on 'static in spawning.md

content/blog/2020-12-tokio-1-0.md
[Rendered](https://deploy-preview-526--tokio.netlify.app/blog/2020-12-tokio-1-0)
=> blog: write Tokio 1.0 announcement

content/tokio/tutorial/select.md
Thank you for this excellent tutorial!
=> Fix a couple of typos in "select" tutorial chapter

components/content.tsx
This allows users of assistive technology to more easily navigate backwards and forwards through e.g. the tutorial.
=> Mark up next/previous page links

content/tokio/tutorial/hello-tokio.md
Add instruction to install "mini-redis-server" before running it.
=> Install "mini-redis-server" before running

content/tokio/tutorial/hello-tokio.md, tutorial-code/hello-tokio/Cargo.toml, tutorial-code/hello-tokio/src/main.rs
This implements a change suggested by Alice here: https://users.rust-lang.org/t/after-3-months-still-learning-to-read-rust-code/55616/12?u=mvolkmann
=> .into -> Bytes::from

content/tokio/tutorial/channels.md
This PR fixes a minor typo in channels.md
=> Fixes typo in channels.md

content/tokio/tutorial/async.md
=> Update text in async-in-depth

content/blog/2021-05-14-inventing-the-service-trait.md
A few people asked about this on reddit so thought I would amend the post.
Also fixed another few typos someone noticed.
=> Clarify why using `Fn`s wont work for defining `Service`

content/blog/2021-05-valuable.md
Rendered: https://deploy-preview-572--tokio.netlify.app/blog/2021-05-valuable
=> blog: announcing valuable

content/blog/2021-05-announcing-tower-http.md
Once https://github.com/tower-rs/tower-http/pull/97 is merged we can publish 0.1.0. 
TODO:
=> blog: announcing tower-http

content/blog/2021-05-valuable.md
Not sure if you wanted North American spelling here :-)
=> Fix a typo in Announcing Valuable: categories -> categorised

content/blog/2017-01-tokio-0-1.md, pages/blog/[...slug].jsx
=> Old blog posts

content/tokio/tutorial/shared-state.md
In the "**Holding a MutexGuard across an .await**" section of the [Shared state tutorial](https://tokio.rs/tokio/tutorial/shared-state), it took me a while to figure out that `MutexGuard` referred to the `lock` (it wasn't stated explicitly in the tutorial). I understood only after I ran the code sample. We can make it clearer for readers by specifying the `MutexGuard` type on `lock`.
=> Clarify which values the MutexGuard refers to

content/tokio/tutorial/spawning.md
=> Update phrasing on static

tutorial-code/channels/src/main.rs
Fix for the issue: https://github.com/tokio-rs/website/issues/577
=> Query same key that was used in "set" command while running the "get" command.

content/tokio/topics/index.md, content/tokio/topics/shutdown.md, pages/[...slug].jsx
[Rendered](https://deploy-preview-589--tokio.netlify.app/tokio/topics/shutdown)
=> Write on graceful shutdown

content/tokio/topics/bridging.md, content/tokio/topics/index.md, netlify.toml, pages/[...slug].jsx
[Rendered](https://deploy-preview-590--tokio.netlify.app/tokio/topics/bridging)
[New redirected link](https://deploy-preview-590--tokio.netlify.app/tokio/tutorial/bridging)
=> Make bridging page a topic article

components/layout.tsx
This also adds a description and will hopefully make the Google result
better.
=> chore: improve homepage title

content/tokio/tutorial/channels.md, tutorial-code/channels/src/main.rs
Otherwise having bytes as a dependency is pointless
=> Update to use Bytes instead of Vec<u8>

tutorial-code/channels/src/main.rs
To inline with https://github.com/tokio-rs/website/blob/master/tutorial-code/channels/src/main.rs#L66
=> chore: fix a typo

content/blog/2021-12-announcing-tokio-console.md
Co-authored-by: Carl Lerche <me@carllerche.com>
Co-authored-by: Felix S Klock II <pnkfelix@pnkfx.org>
=> blog: announcing Tokio Console 0.1

content/blog/2021-12-announcing-tokio-console.md
=> fix relative links

content/tokio/tutorial/shared-state.md
=> Expand on sharded HashMap in shared state

components/footer.tsx
this relates to this #468 any further changes I would be glad to make
=> #468 Included netilify link 

content/blog/2021-05-14-inventing-the-service-trait.md
Added task::spawn to the example Server implementations to illustrate how it would handle concurrent requests.
Addresses #658.
=> Add task::spawn to concurrent examples

content/tokio/topics/index.md, content/tokio/topics/tracing.md, doc-test/Cargo.toml, pages/[...slug].jsx
Adds a (brief) _Getting started with Tracing_ guide.
=> Add topic 'Getting started with Tracing'.

content/blog/2022-08-whats-new-in-axum-0-6-0-rc1.md
[🖼 Rendered](https://github.com/tokio-rs/website/blob/david/axum-0.6/content/blog/2022-08-whats-new-in-axum-0-6.md)
=> blog: whats new in axum 0.6.0-rc.1

content/blog/2022-11-24-announcing-axum-0-6-0.md, content/blog/2022-11-25-announcing-axum-0-6-0.md
axum 0.6.0 is feature complete and I expect to ship it tomorrow 🎉 
cc @jplatte
=> blog: announcing axum 0.6.0

content/blog/2023-01-03-announcing-turmoil.md
Rendered: https://deploy-preview-684--tokio.netlify.app/blog/2023-01-03-announcing-turmoil
=> blog: announce turmoil

content/tokio/topics/bridging.md
Reference: https://github.com/tokio-rs/mini-redis/pull/119
=> Update the doc for blocking client

components/content.tsx, content/blog/2017-01-tokio-0-1.md, content/blog/2017-03-tokio-io.md, content/blog/2017-09-tokio-reform.md, content/blog/2018-02-tokio-reform-shipped.md, content/blog/2018-03-timers.md, content/blog/2018-03-tokio-runtime.md, lib/api.js, lib/page.js, styles/styles.scss
Added the date of blog entries under the title:
Closes  #637
=> added date under title

content/tokio/tutorial/async.md
=> Tutorial: remove crossbeam, use std channel instead.

content/tokio/topics/bridging.md
add syntax highlight for sample codes
=> Add syntax highlight for sample codes

content/tokio/glossary.md
add syntax highlight for sample codes in glossary section
=> Add syntax highlight for sample codes in glossary section

content/blog/2023-11-27-announcing-axum-0-7-0.md
=> blog: fix date for "announcing axum 0.7"

content/tokio/tutorial/channels.md, content/tokio/tutorial/io.md, content/tokio/tutorial/streams.md
Closes my issue #760 and subsumes the pull request #691. So, it also closes #691.
=> Use $ consistently in bash scripts and apply bash syntax highlighting.

content/tokio/tutorial/framing.md
https://docs.rs/bytes/1.0.0/bytes/trait.BufMut.html worked and https://docs.rs/bytes/1.6.0/bytes/trait.BufMut.html failed but i don't know why.
=> Update link of trait BufMut in framing.md

content/blog/2025-09-26-announcing-tokio-conf-cfp.md
[Rendered](https://deploy-preview-834--tokio.netlify.app/blog/2025-09-26-announcing-tokio-conf-cfp)
=> blog: announce TokioConf CFP
